apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh-config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/RedHatNordicsSA/rhdh-config-gitops
    targetRevision: HEAD
    path: ./manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
